name: Workflow run test

on:
  Workflow_run:
    workflows: [Master Check failure, Master Check success]
    types: [completed]
    branches: [master]
  workflow_dispatch:

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: break build if master check faild
        if: ${{ github.event.Workflow_run.conclusion == 'failure' }}
        run: |
          echo "Master check faild"
          exit 1

  info:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: info
        run: echo "Job Started"


