name: Workflow run test

on:
  Workflow_run:
    workflows: [Master Check failure, Master Check success]
    types: [completed]
    branches: [ master ]
  workflow_dispatch:

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.Workflow_run.conclusion == 'failure' }}
    steps:
      - name: break build
        run: |
          echo "Master check faild"
          exit 1


  info:
    runs-on: ubuntu-latest
    needs: on-failure
    steps:
      - name: info
        run: echo "Job Started"


